package jorg.gui.statistics;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import jorgcore.database.DataBase;

public class Statistics extends javax.swing.JFrame {

    public Statistics() {
        initComponents();
    }

    private int createFileCounterReport(ResultSet rs, PreparedStatement ps) throws SQLException {
        int fileQuantity = 0;
        if (rs.next()) {
            fileQuantity = rs.getInt(1);
        }
        ps.close();
        rs.close();
        return fileQuantity;
    }

    private Map<String, Integer> top10Extensions(Connection con, String sql, PreparedStatement ps, ResultSet rs) throws SQLException {
        sql = "select extension,count(extension) from file group by extension order by count(extension) desc offset 0 rows fetch next 10 rows only ";
        ps = con.prepareStatement(sql);
        rs = ps.executeQuery();
        Map<String, Integer> map = new LinkedHashMap<String, Integer>();
        while (rs.next()) {
            map.put(rs.getString(1), rs.getInt(2));
        }
        ps.close();
        rs.close();
        return map;
    }
    private Date date;

    private String[] olderFile(Connection con, String sql, PreparedStatement ps, ResultSet rs) throws SQLException {
        sql = "select name,size,date_last_modified from file where date_last_modified = (select min(date_last_modified) from file)";
        ps = con.prepareStatement(sql);
        rs = ps.executeQuery();
        String name[] = new String[2];
        if (rs.next()) {
            name[0] = rs.getString(1);
            name[1] = rs.getString(2);
            date = rs.getDate(3);
        }
        ps.close();
        rs.close();
        return name;
    }

    private String[] biggerFile(Connection con, String sql, PreparedStatement ps, ResultSet rs) throws SQLException {
        sql = "select name,size from file where size = (select max(size) from file)";
        ps = con.prepareStatement(sql);
        rs = ps.executeQuery();
        String name[] = new String[2];
        if (rs.next()) {
            name[0] = rs.getString(1);
            name[1] = rs.getString(2);
        }
        ps.close();
        rs.close();
        return name;
    }

    private double createSumarizeOfSize(Connection con, String sql, PreparedStatement ps, ResultSet rs) throws SQLException {
        sql = "select sum(size) from file";
        ps = con.prepareStatement(sql);
        rs = ps.executeQuery();
        double totalSize = 0;
        if (rs.next()) {
            totalSize = rs.getDouble(1) / 1024;
        }
        ps.close();
        rs.close();
        return totalSize;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabPanel = new javax.swing.JTabbedPane();
        jPnNew = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaGeneral = new javax.swing.JTextArea();
        jLblInfo = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtxtAreaGeneral.setBackground(new java.awt.Color(0, 0, 0));
        jtxtAreaGeneral.setColumns(20);
        jtxtAreaGeneral.setFont(new java.awt.Font("Monospaced", 0, 14));
        jtxtAreaGeneral.setForeground(new java.awt.Color(51, 255, 0));
        jtxtAreaGeneral.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaGeneral);

        javax.swing.GroupLayout jPnNewLayout = new javax.swing.GroupLayout(jPnNew);
        jPnNew.setLayout(jPnNewLayout);
        jPnNewLayout.setHorizontalGroup(
            jPnNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnNewLayout.setVerticalGroup(
            jPnNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnNewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabPanel.addTab("General", jPnNew);

        jLblInfo.setFont(new java.awt.Font("Tahoma", 0, 32));
        jLblInfo.setForeground(new java.awt.Color(51, 51, 255));
        jLblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblInfo.setText("Statistics");
        jLblInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                    .addComponent(jLblInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            final Connection con = DataBase.getConnection();
            String sql = "select count(*) from file";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            final int fileQuantity = createFileCounterReport(rs, ps);
            final int unitQuantity = createUnitCounterReport(con, sql, ps, rs);
            final int rentedUnitQuantity = createRentedUnitCounterReport(con, sql, ps, rs);
            final double totalSize = createSumarizeOfSize(con, sql, ps, rs);
            final String[] biggerFile = biggerFile(con, sql, ps, rs);
            final String[] olderFile = olderFile(con, sql, ps, rs);
            final Map<String, Integer> topExtensions = top10Extensions(con, sql, ps, rs);
            Iterator<String> it = topExtensions.keySet().iterator();
            final StringBuilder sb = new StringBuilder();
            sb.append("Top10 Extensions\t\t\t\t\t\t\n");
            sb.append("Ext\t\t\t\t\t\tQuantity\n");
            while (it.hasNext()) {
                String key = it.next();
                Integer value = topExtensions.get(key);
                sb.append(key + "\t\t\t\t\t\t" + value + "\n");
            }



            jtxtAreaGeneral.setText("Quantity of files: " + fileQuantity +
                    "\nUnit quantity: " + unitQuantity +
                    "\nRented Unit quantity: " + rentedUnitQuantity +
                    "\nTotal size: " + NumberFormat.getInstance().format(totalSize / 1024) + " TB (" + NumberFormat.getInstance().format(totalSize) + " GB)" + "\nBigger File: " + biggerFile[0] + " " + NumberFormat.getInstance().format(Double.parseDouble(biggerFile[1])) + " MB" +
                    "\nOlder File: " + olderFile[0] + " " + NumberFormat.getInstance().format(Double.parseDouble(olderFile[1])) + " MB " + new SimpleDateFormat().format(date)+
                    "\n" + sb.toString());
            jtxtAreaGeneral.moveCaretPosition(0);

        } catch (Exception ex) {
            jtxtAreaGeneral.setText(ex.toString());
        }
    }//GEN-LAST:event_formWindowActivated

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Statistics().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblInfo;
    private javax.swing.JPanel jPnNew;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabPanel;
    private javax.swing.JTextArea jtxtAreaGeneral;
    // End of variables declaration//GEN-END:variables

    private int createUnitCounterReport(Connection con, String sql, PreparedStatement ps, ResultSet rs) throws SQLException {
        sql = "select count(*) from unit";
        ps = con.prepareStatement(sql);
        rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getInt(1);
        }
        ps.close();
        rs.close();
        return 0;
    }

        private int createRentedUnitCounterReport(Connection con, String sql, PreparedStatement ps, ResultSet rs) throws SQLException {
        sql = "select count(*) from unit where rented_to is not null";
        ps = con.prepareStatement(sql);
        rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getInt(1);
        }
        ps.close();
        rs.close();
        return 0;
    }

}
